services:
  - type: web
    name: trivity-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false
